name: Android CI (Multiplatform)

on:
  push:
    branches: [ "development" ]
    paths:
      - "multiplatform/**"
      - ".github/workflows/android-ci.yml"

  pull_request:
    branches: [ "main" ]
    paths:
      - "multiplatform/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: multiplatform
        run: chmod +x gradlew

      - name: Build
        working-directory: multiplatform
        run: ./gradlew build

      - name: Run tests
        working-directory: multiplatform
        run: ./gradlew test
